server {
	listen 4242;
	server_name halnuma.42.fr; 
	host localhost;
	root website/;
	index index.html;
	#test comment
	error_page 404.html;
	client_max_body_size 10;

	location / {
		allow_methods GET;
		autoindex on;
	}

	location /test {
		allow_methods GET POST;
	}
}

server {
	listen 3334;
	server_name secros.42.fr; 
	host localhost;
	root ./YoupiBanane/;
	index index.html;
	#test comment
	error_page 404.html;
	client_max_body_size 1;

	location / {
		index youpi.bla;
		allow_methods GET;
	}
	# location /redi {
	# 	return 301 /directory/;
	# }

	location /directory/ {
		root usr/home/halnuma/documents/cursus/webserv/YoupiBanane
		index youpi.bad_extension
		allow_methods GET;
	}

	location /post_body {
		allow_methods POST;
	}

	location .bla {
        allow_methods POST;
        cgi_ext .bla;
        cgi_path usr/home/halnuma/documents/cursus/webserv/cgi_test;
    }
}

server {
	listen 3332;
	root website/;
	index blog.html;
	#test comment
	error_page 404.html;
	client_max_body_size 20000000;

	location /test {
		return 301 /ya;
	}

	location /ya {
		allow_methods GET;
		autoindex on;
	}

	location /yo {
		root path/;
		allow_methods GET POST;
	}

	location /yo/yes {
		root website/;
		allow_methods GET POST;
	}

	location /yo/ya {
		root path/;
		allow_methods GET POST;
	}

	location /yo/yes/oui {
		root path/;
		allow_methods GET POST;
	}

	location /cgi-bin {
		cgi_ext .py;
		cgi_path /usr/bin/python3;
	}

	location .php {
        allow_methods GET POST;
        cgi_ext .php;
        cgi_path /usr/bin/php-cgi;
    }

	location .py {
		root website/script/
        allow_methods GET POST;
        cgi_ext .py;
        cgi_path /usr/bin/python3;
    }
}

server {
	listen 3331;
	root website/;
	index index.html;
	#test comment
	error_page 404.html;
	client_max_body_size 10;

	location /test {
		return 301 /ya;
	}

	location 4 {
		allow_methods GET;
		autoindex off;
	}

	location /ya {
		allow_methods GET;
		autoindex on;
	}

	location /yo {
		root path/;
		allow_methods GET POST;
	}

	location /yo/yes {
		root website/;
		allow_methods GET POST;
	}

	location /yo/ya {
		root path/;
		allow_methods GET POST;
	}

	location /yo/yes/oui {
		root path/;
		allow_methods GET POST;
	}

	location /cgi-bin {
		cgi_ext .py;
		cgi_path /usr/bin/python3;
	}

	location .php {
        allow_methods GET POST;
        cgi_ext .php;
        cgi_path /usr/bin/php-cgi;
    }

	location .py {
		root website/script/
        allow_methods GET POST;
        cgi_ext .py;
        cgi_path /usr/bin/python3;
    }
}
