server {
	listen 4242;
	host localhost;
	root website/;
	index index.html;
	client_max_body_size 20000000;
	error_page 404 /error_pages/404.html;
	location / {
		allow_methods GET POST;
		autoindex on;
	}

	location /test {
		allow_methods GET POST;
	}
}

server {
	listen 8081;
	root website/;
	client_max_body_size 20000000;
	error_page 404 /error_pages/404.html;
	location / {
		autoindex on;
	}

	location /test/ {
		return 301 /yo/;
	}

	location /yo/ {
		index index.html;
		allow_methods GET;
	}

	location /uploads/ {
		root website/uploads/;
		autoindex on;
	}

	location /yo/yes/ {
		root website/;
		allow_methods GET POST;
	}

	location .py {
		root website/script/;
        allow_methods GET POST;
        cgi_ext .py;
        cgi_path /usr/bin/python3;
    }
    
    location .sh {
		root website/script/;
        allow_methods GET POST;
        cgi_ext .sh;
        cgi_path /usr/bin/bash;
    }
}
